name: zenith_education_app
description: A new Flutter project for Ethiopian high school students.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.1.1

  # Navigation
  go_router: ^6.0.1

  # Firebase
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.2.0
  firebase_storage: ^11.0.10
  firebase_crashlytics: ^3.0.10

  # Local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI and utilities
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  cached_network_image: ^3.2.1

  # Charts
  fl_chart: ^0.55.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true